TAP_DANCE_ENABLE = yes
CAPS_WORD_ENABLE = yes
ENCODER_MAP_ENABLE = yes

COMBO_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no

USER_KEYRECORDS_ENABLE = yes
USER_TAP_DANCE_ENABLE = yes

RGB_MATRIX_CUSTOM_USER = yes
CUSTOM_RGB_MATRIX_INDICATOR = yes
CUSTOM_RGB_MATRIX = yes
